### ISSUE TITLE
hi fatal error etc/vendor/autoload.php

### ISSUE THREAD

**Issue by yyaman91** [rosasurfer/mt4-tools#4]
Warning: require(C:\wamp\www\yy\app/../etc/vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\yy\app\init.php on line 6

I didn't composer but I downloaded but fatal error etc/vendor/autoload.php 
What should i do

**Comment by rosasurfer** [comment]
Well, you *have* to run composer first, no matter if you cloned or downloaded :)

git clone ...
cd mt4-tools
composer install

For composer instructions look here: https://getcomposer.org/download/

The project is still in it early stages, you find an online version here:
http://xtrade.rosasurfer.com

**Comment by yyaman91** [comment]
this project use

Please take a a look into WebServices available commands description:
https://support.metaquotes.net/en/docs/mt4/api/
webservices_api/web_api_command

You can also find small example of trader's private room there:
https://support.metaquotes.net/en/articles/20

Accounts can be opened using WebRegistration Server API
<https://support.metaquotes.net/en/docs/mt4/api/server_api> plugin. More
information: https://support.metaquotes.net/en/articles/57

Trading operations are no possible using WebServices API, you can develop
your own solution using Manager API
<https://support.metaquotes.net/en/docs/mt4/api/manager_api>.


manager api with user info ,user history, trader buy and sell can?

2017-07-13 14:03 GMT+03:00 Peter Walther <notifications@github.com>:

**Comment by rosasurfer** [comment]
Thanlk you. The project's target audience are not only users of MT4 but also users of other platforms. The "MT4" in it's name is to make it more easy to find the project (the majority will be MetaTrader users). Said that, I have no intention to work with MetaQuotes. In fact the goal was to be independant of them.
